version: "3"
services:

  test-app:
    image: soika/docker-java-memory-test
    ports:
      - "8080:8080"

    deploy:
      resources:
        limits:
          memory: 370M
        reservations:
          memory: 200M
 

    
 